### ISSUE TITLE
Internal Server Error in Dashboard

### ISSUE THREAD

**Issue by oss-aimoto** [openam-jp/openam#209]
## Description
* Internal Server Error in Dashboard
* "FIDO2 (WebAuthn) Authentication Devices" is not displayed

![InternaleServerError](https://user-images.githubusercontent.com/37646647/79096469-3cfdfa00-7d98-11ea-8219-4204d60eeb9c.png)

## Steps to reproduce
1. Complete OpenAM setup
2. Log in as demo user
3. Click the dashboard link

The idm cache affects.
The following settings will always be reproduced.

* [CONFIGURE] - [SERVER DEFAULTS] - [Advanced]

```
com.sun.identity.idm.cache.entry.default.expire.time=0
com.sun.identity.idm.cache.entry.expire.enabled=true
com.sun.identity.idm.cache.entry.user.expire.time=0
```

## Enviroment
* OpenAM 14.0.0 Build 0f2fda8adb (2019-December-23 09:11)

## Debug Log
* CoreSystem
```
frRest:04/13/2020 06:11:07:621 AM UTC: Thread[http-bio-8443-exec-7,5,main]: TransactionId[e7340f36-82b7-467d-a175-c7082023854f-103]
ERROR: WebAuthnDevicesResource :: Query - Unable to retrieve identity data from request context
org.forgerock.json.resource.InternalServerErrorException: getIdentity : User id=demo,ou=user,dc=openam,dc=osstech,dc=co,dc=jp is not found
	at jp.co.osstech.openam.core.rest.devices.services.webauthn.WebAuthnDevicesResource.getIdentity(WebAuthnDevicesResource.java:237)
	at jp.co.osstech.openam.core.rest.devices.services.webauthn.WebAuthnDevicesResource.queryCollection(WebAuthnDevicesResource.java:156)
	at org.forgerock.json.resource.InterfaceCollectionHandler.handleQuery(InterfaceCollectionHandler.java:62)
	at org.forgerock.json.resource.Router.handleQuery(Router.java:310)
	at org.forgerock.json.resource.Router.handleQuery(Router.java:310)
	at org.forgerock.json.resource.FilterChain$Cursor.handleQuery(FilterChain.java:99)
	at org.forgerock.authz.filter.crest.AuthorizationFilters$AuthorizationFilter$5.apply(AuthorizationFilters.java:350)
	at org.forgerock.authz.filter.crest.AuthorizationFilters$AuthorizationFilter$5.apply(AuthorizationFilters.java:346)
〜
Caused by: Message:getIdentity : User id=demo,ou=user,dc=openam,dc=osstech,dc=co,dc=jp is not found

	at jp.co.osstech.openam.core.rest.devices.services.webauthn.WebAuthnDevicesResource.getIdentity(WebAuthnDevicesResource.java:230)
	... 107 more

```

**Comment by tsujiguchitky** [comment]
If there was no user cache, the following search was occurred.

```
[18/Jun/2020:13:02:25 +0900] SEARCH REQ conn=15 op=18 msgID=19 base="ou=people,dc=openam,dc=jp" scope=sub filter="(&(uid=id=demo,ou=user,dc=openam,dc=jp)(objectclass=inetorgperson))" attrs="dn"
[18/Jun/2020:13:02:25 +0900] SEARCH RES conn=15 op=18 msgID=19 result=0 nentries=0 etime=1
```

In this search, universal id (DN format) was used for LDAP filter instead of user id. 

In WebAuthnDevicesResource, `userName` variable has a DN format value. This affects incorrect search.

```
 148     @Override
 149     public Promise<QueryResponse, ResourceException> queryCollection(Context cntxt, QueryRequest qr, QueryResourceHandler qrh) {
 150         final Subject subject = getContextSubject(cntxt);
 151         String userName = subject.getPrincipals().iterator().next().getName(); // userName is `id=demo,ou=user,dc=openam,dc=jp`
```
