### ISSUE TITLE
SAML2 authentication does not work when SAML2 failover is enabled.

### ISSUE THREAD

**Issue by tsujiguchitky** [openam-jp/openam#40]
## Description

Enabling SAML2 failover causes authentication error in the SAML2 authentication module.
According to the debug log, this looks like a deserialization problem for CTS.

## Steps to reproduce

1) Prepare a SAML IdP
2) Configure OpenAM as a SAML SP
3) Configure the SAML2 Authentication Module
4) Enable SAML2 Failover
5) Access the SAML2 authentication module
6) Authenticate on IdP

## Expected Results

SAML2 Authentication is successful, and the profile screen is displayed.

## Actual Results

Login failure screen is displayed.

## Debug Log

When the debug log is set to the information level, the following stack trace is output.

```
amAuth:03/25/2019 05:14:10:002 PM JST: Thread[http-bio-8080-exec-16,5,main]: TransactionId[182f3d83-450f-438e-be13-1af4887a4093-867]
Exception
javax.security.auth.login.LoginException: java.lang.IllegalStateException: Failed to deserailise SAML2ResponseData
        at org.forgerock.openam.cts.utils.JSONSerialisation.deserialise(JSONSerialisation.java:93)
        at org.forgerock.openam.cts.adapters.SAMLAdapter.fromToken(SAMLAdapter.java:118)
        at org.forgerock.openam.cts.adapters.SAMLAdapter.fromToken(SAMLAdapter.java:36)
        at org.forgerock.openam.cts.impl.SAML2CTSPersistentStore.retrieveSAML2Token(SAML2CTSPersistentStore.java:87)
        at com.sun.identity.saml2.common.SAML2FailoverUtils.retrieveSAML2Token(SAML2FailoverUtils.java:80)
        at org.forgerock.openam.authentication.modules.saml2.SAML2.handleReturnFromRedirect(SAML2.java:312)
        at org.forgerock.openam.authentication.modules.saml2.SAML2.process(SAML2.java:189)
        at com.sun.identity.authentication.spi.AMLoginModule.wrapProcess(AMLoginModule.java:1056)
        at com.sun.identity.authentication.spi.AMLoginModule.login(AMLoginModule.java:1224)
        ...
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.sun.identity.saml2.profile.ResponseInfo` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"assertion":{"advice":null,"attributeStatements":[],"authnStatements":[{"authnContext":{"authenticatingAuthority":null,"authnContextClassRef":"urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport","authnContextDecl":null,"authnContextDeclRef":null,"mutable":false},"authnInstant":1553501649000,"mutable":false,"sessionIndex":"s2d2f54e055f009cb96dc3fcbe50ebf08648793e01","sessionNotOnOrAfter":null,"subjectLocality":null}],"authzDecisionStatements":[],"conditions":{"audienceRestrictions"[truncated 15227 chars]; line: 1, column: 6942] (through reference chain: org.forgerock.openam.authentication.modules.saml2.SAML2ResponseData["responseInfo"])
        ...
```

## References

[[OPENAM-9432] SAML2 authentication module not functioning as expected when SAML2 Failover is enabled](https://bugster.forgerock.org/jira/browse/OPENAM-9432)

**Comment by Iwakata** [comment]
Deserialization fails because,

- `ResponseInfo` class does not have the default constructor.

- Concrete types for `Response`, `Status` and `StatusCode` interfaces can not be determined during deserialization.

We need to provide necessary information for these.
