### ISSUE TITLE
Can not edit policy using IE11

### ISSUE THREAD

**Issue by tsujiguchitky** [openam-jp/openam#54]
## Description

If OpenAM is deployed on a relatively new Tomcat and using IE11 as a client, you can not edit the policy in the admin console.

When comparing Firefox and IE11 requests, I know that there is a difference in the requests to `/openam/json/policies`. In IE11, double quote is not encoded and HTTP 400 is returned (normally HTTP 200 is returned).

### Forefox

`
http://openam14.example.co.jp:8080/openam/json/policies?_pageSize=20&_sortKeys=name&_queryFilter=applicationName+eq+%22iPlanetAMWebAgentService%22&_pagedResultsOffset=0
`

### IE11

`
http://openam14.example.co.jp:8080/openam/json/policies?_pageSize=20&_sortKeys=name&_queryFilter=applicationName+eq+"iPlanetAMWebAgentService"&_pagedResultsOffset=0
`

## Steps to reproduce

Access admin console with IE11 and edit the policies.

## Expected Results
You can edit policies.

## Actual Results
You can not view the policy list and can not create/edit/delete the policies.

## Enviroment

* Server
  * CentOS 7.5
  * tomcat-7.0.76-9.el7_6.noarch
* Client
  * Windows 10 Pro Ver.1809
  * IE 11.437.17763.0

## Log

When a problem occurs, Tomcat logs the following error:

```
Apr 16, 2019 3:28:28 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:189)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1000)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

## References

* [[OPENAM-11666] Accessing XUI using IE fails on some REST URI like creating Auth Module](https://bugster.forgerock.org/jira/browse/OPENAM-11666)

**Comment by tsujiguchitky** [comment]
Similar problems occur when creating authentication modules, as described in References.
In addition, Bad Request occurs on the resource page of the end user profile screen when UMA provider is enabled.

These similar issues also need to be fixed.
